---
- name: Ensure cronie is installed
  become: true
  package:
    name: cronie
    state: present

- name: Ensure cronie service is enabled and started
  become: true
  service:
    name: cronie
    state: started
    enabled: true

- name: Ensure dotfiles repo is present
  git:
    repo: https://github.com/thadigus/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    update: true

- name: Apply GNU stow dotfiles script
  shell: "/bin/bash -c '{{ dotfiles_dir }}/scripts/arch_dotfiles.sh'"

- name: Ensure dotfiles update-on-reboot cron exists
  cron:
    name: Update Dotfiles on Reboot
    special_time: reboot
    job: "sudo -u {{ ansible_facts['env']['USER'] }} {{ dotfiles_dir }}/scripts/arch_logon.sh"
