# Ansible Pull Playbook for Deploying My Workstations
#

---

- hosts: localhost
  connection: local
  tasks:
    - name: Block - Arch Linux Configuration
      block:
        - name: Ensure git is present for local clone
          become: true
          package:
            name:
              - git
            state: present

        - name: Clone dotfiles repo to home
          git:
            repo: https://github.com/thadigus/dotfiles.git
            dest: "{{ ansible_env.HOME }}/dotfiles"
            update: true

        - name: Run split Arch playbook from local clone
          shell: >
            ansible-playbook -i localhost, -c local
            "{{ ansible_env.HOME }}/dotfiles/ansible/arch_site.yml"
      when: ansible_os_family == "Archlinux"
    - name: Block - MacOS Configuration
      block:
        - name: Ensure git is present for local clone
          package:
            name:
              - git
            state: present

        - name: Clone dotfiles repo to home
          git:
            repo: https://github.com/thadigus/dotfiles.git
            dest: "{{ ansible_env.HOME }}/dotfiles"
            update: true

        - name: Run split MacOS playbook from local clone
          shell: >
            ansible-playbook -i localhost, -c local
            "{{ ansible_env.HOME }}/dotfiles/ansible/macos_site.yml"
      when: ansible_os_family == "Darwin"
