- name: Set tuigreet in greetd config
  become: true
  shell: |
    cat << EOF > /etc/greetd/config.toml
    [terminal]
    vt = 1

    [default_session]
    command = "tuigreet --config /etc/tui-greetd/config.toml --cmd /home/thadigus/dotfiles/scripts/arch_start_dwl.sh"
    user = "greeter"
    EOF
- name: Add tuigreet Config
  become: true
  copy:
    src: "{{ dotfiles_dir }}/tui-greetd/config.toml"
    dest: "/etc/greetd/tui-greetd.toml"

- name: Ensure /etc/greetd Permissions
  become: true
  file:
    path: /etc/greetd
    owner: greeter
    group: greeter
    mode: '0740'
    recurse: yes
