- name: Set tuigreet in greetd config
  become: true
  shell: |
    cat << EOF > /etc/greetd/config.toml
    [default]
    path = "/usr/bin/tui-greetd"
    args = [
        "--config", "/etc/greetd/tui-greetd.toml"
    ]
    user-session = "sway"
    EOF

- name: Add tuigreet Config
  become: true
  cp:
    src: "{{ dotfiles_dir }}/tui-greetd/config.toml"
    dest: "/etc/greetd/tui-greetd.toml"

- name: Ensure /etc/greetd Permissions
  become: true
  file:
    path: /etc/greetd
    owner: greeter
    group: greeter
    mode: '0740'
    recurse: yes
